# @file: .pre-commit-config.offline.yaml
      - id: isort
        name: isort
        entry: python -m isort
        language: system
        types: [python]
      - id: black
        name: black
        entry: python -m black
        language: system
        types: [python]
