# @file: .pre-commit-config.offline.yaml
# @description: Local pre-commit hooks for offline linting
# @dependencies: .pre-commit-config.yaml
# @created: 2025-09-17

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff (check + fix)
        entry: python -m ruff check
        args: [--fix, --exit-non-zero-on-fix]
        language: system
        types: [python]
      # - id: ruff-format
      #   name: ruff (format)
      #   entry: python -m ruff format
      #   language: system
      #   types: [python]
      - id: black
        name: black
        entry: python -m black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: python -m isort
        language: system
        types: [python]
      - id: trailing-whitespace
        name: trailing-whitespace
        entry: scripts/hooks/trailing_ws.py
        language: system
        types: [text]
      - id: end-of-file-fixer
        name: end-of-file-fixer
        entry: scripts/hooks/eof_fixer.py
        language: system
        types: [text]
