# @file: .pre-commit-config.offline.yaml
# @description: Local pre-commit hooks for offline linting
# @dependencies: .pre-commit-config.yaml
# @created: 2025-09-17

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python -m black
        language: system
        types: [python]
      - id: isort
        name: isort
        entry: python -m isort
        language: system
        types: [python]
