# @file: ruff.toml
# @description: Ruff configuration
# @dependencies: none
# @created: 2025-09-10

line-length = 88
target-version = "py310"

[lint]
select = ["E", "F", "I", "B"]

[format]
quote-style = "double"
indent-style = "space"
