line-length = 100
target-version = "py311"
extend-select = ["I","B","C4","UP","PT","ERA","F"]
ignore = ["E501"]  # переносы строк — на откуп black
extend-exclude = ["legacy/","experiments/","notebooks/","scripts/migrations/"]
[per-file-ignores]
"**/__init__.py" = ["F401","F403"]
"tests/**" = ["F401"]
