line-length = 100
target-version = "py311"
extend-select = ["I", "B", "C4", "UP", "PT", "ERA", "F"]
ignore = ["E501"]
extend-exclude = [
  "legacy/",
  "experiments/",
  "notebooks/",
  "scripts/migrations/",
]
# Внимание: никаких секций [isort] здесь не указывать — ruff их не понимает.
