# @file: .github/workflows/ci.yml
# @description: CI workflow running linting, formatting, smoke checks, and unit tests
# @dependencies: requirements.txt, scripts/run_start_check.sh
# @created: 2025-08-24

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  pr-smoke:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      SPORTMONKS_STUB: "1"
      SPORTMONKS_API_KEY: dummy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install project dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install -e .[dev,ml,migrations]

      - name: Smoke check
        env:
          ROLE: "O'Reilly"
        run: scripts/run_start_check.sh

      - name: Get changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.py

      - name: Apply formatting to changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          files=$(printf '%s' "${{ steps.changed-files.outputs.all_changed_files }}")
          python -m ruff check --fix $files
          python -m black $files
          python -m isort $files

      - name: Run formatting checks on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          files=$(printf '%s' "${{ steps.changed-files.outputs.all_changed_files }}")
          python -m ruff check $files
          python -m black --check $files
          python -m isort --check-only $files

      - name: No Python file changes detected
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No Python files changed; skipping style steps."

      - name: Pytest smoke subset
        run: python -m pytest tests/test_sportmonks_stub.py

  main-full:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      SPORTMONKS_STUB: "1"
      SPORTMONKS_API_KEY: dummy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install project dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install -e .[dev,ml,migrations]

      - name: Smoke check
        env:
          ROLE: "O'Reilly"
        run: scripts/run_start_check.sh

      - name: Pytest full suite
        run: python -m pytest -q
