# @file: .github/workflows/ci.yml
# @description: CI workflow running linting, formatting, smoke checks, and unit tests
# @dependencies: requirements.txt, scripts/run_start_check.sh
# @created: 2025-08-24

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  style-and-tests-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    env:
      SPORTMONKS_STUB: "1"
      SPORTMONKS_API_KEY: dummy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install tooling and project dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install -e .[dev,ml,migrations]

      - name: Smoke check role dispatch
        env:
          ROLE: "O'Reilly"
        run: scripts/run_start_check.sh

      - name: Get changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.py

      - name: Apply formatting to changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          files=$(printf '%s' "${{ steps.changed-files.outputs.all_changed_files }}")
          python -m ruff check --fix $files
          python -m black $files
          python -m isort $files

      - name: Run formatting checks on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          files=$(printf '%s' "${{ steps.changed-files.outputs.all_changed_files }}")
          python -m ruff check $files
          python -m black --check $files
          python -m isort --check-only $files

      - name: No Python file changes detected
        if: steps.changed-files.outputs.any_changed != 'true'
        run: echo "No Python files changed; skipping style steps."

      - name: Pytest
        run: python -m pytest -q

  style-and-tests-main:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    env:
      SPORTMONKS_STUB: "1"
      SPORTMONKS_API_KEY: dummy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install tooling and project dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install -e .[dev,ml,migrations]

      - name: Smoke check role dispatch
        env:
          ROLE: "O'Reilly"
        run: scripts/run_start_check.sh

      - name: Ruff autofix
        run: python -m ruff check . --fix

      - name: Black format
        run: python -m black .

      - name: isort format
        run: python -m isort .

      - name: Ruff check
        run: python -m ruff check .

      - name: Black check
        run: python -m black --check .

      - name: isort check
        run: python -m isort --check-only .

      - name: Pytest
        run: python -m pytest -q
