# @file: .github/workflows/ci.yml
# @description: CI workflow running linting and tests across Python versions with pip cache
# @dependencies: .pre-commit-config.yaml, requirements.txt
# @created: 2025-08-24

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Lint (online with offline fallback)
        run: |
          make pre-commit-smart || {
            ruff . && isort --check --diff . && black --check .
          }

  unit:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Tests
        env:
          SPORTMONKS_STUB: 1
          SPORTMONKS_API_KEY: dummy
        run: pytest -q

  e2e_smoke:
    needs: unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Smoke tests
        run: make smoke
      - name: E2E test
        run: pytest -q tests/test_prediction_pipeline_local_registry_e2e.py

  numeric:
    needs: e2e_smoke
    runs-on: ubuntu-latest
    env:
      PIP_CONFIG_FILE: pip.conf
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Numeric tests
        run: |
          output=$(pytest -m needs_np -q -rs)
          echo "$output"
          if echo "$output" | grep -i 'skipped'; then
            echo 'Numeric tests were skipped'
            exit 1
          fi
      - name: Validate modifiers improvement
        env:
          SEASON_ID: "${{ env.SEASON_ID || 'default' }}"
          TOL_LOSS: "0.00"
          TOL_ECE: "0.00"
        run: |
          python scripts/validate_modifiers.py --season-id "${SEASON_ID}" --input data/val.csv --alpha 0.005 --l2 1.0 --tol "${TOL_LOSS}" --tol-ece "${TOL_ECE}"
      - name: Upload simulation artifacts
        uses: actions/upload-artifact@v3
        with:
          name: metrics-and-artifacts
          path: |
            reports/metrics/**/*.md
            reports/metrics/**/*.png
            artifacts/**/*
            var/predictions.sqlite
          retention-days: 14
