# @file: .github/workflows/ci.yml
# @description: Continuous integration workflow for linting, smoke checks, and targeted pytest suites
# @dependencies: requirements.txt, constraints.txt, Makefile, scripts/run_start_check.sh
# @created: 2025-02-15

name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: "role: ${{ matrix.role }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        role: [web, worker]
    env:
      ROLE: ${{ matrix.role }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f constraints.txt ]; then
            python -m pip install -r requirements.txt -c constraints.txt
          else
            python -m pip install -r requirements.txt
          fi
          python -m pip install -e .[dev]

      - name: Run make check
        run: make check

      - name: Smoke test
        env:
          TELEGRAM_BOT_TOKEN: "test_dummy"
          SPORTMONKS_API_TOKEN: "test_dummy"
        run: scripts/run_start_check.sh

      - name: Run targeted pytest suite
        run: pytest -m "requires_fastapi or integrations" -q
