# @file: .github/workflows/ci.yml
# @description: CI workflow running linting and tests across Python versions with pip cache
# @dependencies: .pre-commit-config.yaml, requirements.txt
# @created: 2025-08-24

name: CI

env:
  APP_VERSION: v1.0.0-rc1
  GIT_SHA: ${{ github.sha }}

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      SPORTMONKS_STUB: "1"
      SPORTMONKS_API_KEY: dummy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install ruff black isort pytest pytest-cov

      - name: lint
        run: |
          python -m ruff check .
          python -m black --check .
          python -m isort --check-only .

      - name: test-fast
        run: make test-fast

      - name: smoke
        run: make test-smoke

      - name: coverage
        run: make coverage-html

      - name: coverage-enforce
        run: python -m tools.coverage_enforce --summary-json reports/coverage_summary.json

      - name: reports
        run: |
          python reports/bot_e2e_snapshot.py
          python reports/rc_summary.py --tests-passed --summary-json reports/coverage_summary.json

      - name: artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-reports
          path: |
            htmlcov/**
            reports/bot_e2e_snapshot.md
            reports/rc_summary.json
            reports/coverage_summary.json
          retention-days: 14
