# @file: .github/workflows/ci.yml
# @description: CI workflow running linting, formatting, smoke checks, and unit tests
# @dependencies: requirements.txt, scripts/run_start_check.sh
# @created: 2025-08-24

name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    env:
      SPORTMONKS_STUB: "1"
      SPORTMONKS_API_KEY: dummy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Install tooling and project dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          python -m pip install ruff black isort pytest

      - name: Smoke check role dispatch
        env:
          ROLE: "O'Reilly"
        run: scripts/run_start_check.sh

      - name: Ruff autofix
        run: python -m ruff check . --fix

      - name: Black format
        run: python -m black .

      - name: isort format
        run: python -m isort .

      - name: Ruff check
        run: python -m ruff check .

      - name: Black check
        run: python -m black --check .

      - name: isort check
        run: python -m isort --check-only .

      - name: Pytest
        run: python -m pytest -q
